### PR TITLE
Missing underscore in GMAPS_API_KEY variable from README

### PR DESCRIPTION
**Pull request by mariusmotea**

### CODE REVIEW

**Comment by pierrecdn** [comment]
Hi, thanks for this,
Could you just polish the commit message & body ("Fix typo on environment variable" and "GMAPS_API_KEY missed the underscore in the readme" for example)? Then I'll merge it right away.

**Comment by mariusmotea** [comment]
From mobile it don't allow me to edit the name, i will try in a few hours from my pc.

**Comment by mariusmotea** [comment]
Done! Hope it is ok now.

**Comment by pierrecdn** [comment]
I was more thinking of amending the commit itself, not the PR ;).
It's easier to backlog things with git and avoid scrolling github issues all the day.

**Pull request closed without merging**
