### PR TITLE
Update version to 1.4.4

### PR DESCRIPTION
**Pull request by holishing**
https://github.com/phpipam/phpipam/releases

```
1.4.4 Bugfixes:
----------------------------
+ Allow UTF-8 in instruction widgets (#3360);
+ Exclude IPv6 from Ping and Discovery scans (#3354);

Security Fixes:
----------------------------
+ XSS (reflected) in IP calculator (#3351);
+ XSS in pass-change/result.php (#3373);


1.4.3 Bugfixes:
----------------------------
+ FPing discovery marks all addresses as alive (#2888);
+ SNMP, number of discovered hosts exceed maximum warning (#3279);

Security Fixes:
----------------------------
+ PHP session ID fixation (#3342);
```

### CODE REVIEW

**Comment by pierrecdn** [comment]
Thanks, merged.

**Comment by holishing** [comment]
Thanks!  But it seems like the upgraded version is not automatically built and pushed to Docker Hub?

**Comment by pierrecdn** [comment]
Apparently Docker Hub [recently disabled autobuilds](https://www.docker.com/blog/changes-to-docker-hub-autobuilds/).
I'll need to setup Github Actions instead to do the job.
EDIT: Done now.

**Comment by holishing** [comment]
Thank you!

**Pull request merged**
