### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by pipo2906**

### CODE REVIEW

**Comment by pierrecdn** [comment]
Hi,
I understand you're trying to change the locale for some reason.
I cannot merge such PR simply because it's specific to your use case.
I would advice you to create a wrapper image on your side using "FROM pierrecdn:phpipam" then your RUN/ENV directives.

**Comment by pipo2906** [comment]
Hey
thanks for the tip. Of course I can understand that. is not a problem, I hope I did not cause them any stress.

Von meinem iPhone gesendet

**Comment by pipo2906** [comment]
Hey,

Hey, I have a problem. When I create an image on git hub and then clone I always get this message.
Can you tell me what I'm doing wrong.


Package php5-gmp is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'php-pear' has no installation candidate
E: Package 'php5-curl' has no installation candidate
E: Package 'php5-mysql' has no installation candidate
E: Package 'php5-json' has no installation candidate
E: Package 'php5-gmp' has no installation candidate
E: Package 'php5-mcrypt' has no installation candidate
E: Package 'php5-ldap' has no installation candidate
E: Package 'php5-gd' has no installation candidate
E: Package 'php-net-socket' has no installation candidate


I hope you can help me.

**Comment by pierrecdn** [comment]
Hi,
Yes it's because docker library/php maintainer suddenly decided to break debian package installations by pushing an apt preferences file, the consequence being in some cases to have multiple php installs on the container.
I'll push a quick workaround, even though a better approach would be to repackage this image using alpine, install from sources / pecl, etc.

**Pull request closed without merging**
