### PR TITLE
Release version update and Version change from ENV to ARG

### PR DESCRIPTION
**Pull request by leleobhz**
Hello!

This PR aims 2 objectives:

* Update 1.5.0 to 1.5.1 (Release fixes)
* Allow set version of phpipam and some dependencies without need to fork if structures does not changes.

It's possible to you @pierrecdn to accept this PR?

Thank you!

### CODE REVIEW

**Comment by leleobhz** [comment]
Just a note: I kept intermediate commits to "tell a history". I can fixup all this commits if author prefers.

**Comment by pierrecdn** [comment]
Hi, Thanks for that!

> It's possible to you @pierrecdn to accept this PR?

Sure, overall changes seems perfectly OK to me.

> Just a note: I kept intermediate commits to "tell a history".

Yes, that's great to keep track of each change individually and keep a clean commit message on each of them.

> I can fixup all this commits if author prefers.

I would prefer that you fix up the ones that are related indeed (such as ENV/ARG and the SAML thing). Thanks.

**Comment by leleobhz** [comment]
> Hi, Thanks for that!
> 
> > It's possible to you @pierrecdn to accept this PR?
> 
> Sure, overall changes seems perfectly OK to me.
> 
> > Just a note: I kept intermediate commits to "tell a history".
> 
> Yes, that's great to keep track of each change individually and keep a clean commit message on each of them.
> 
> > I can fixup all this commits if author prefers.
> 
> I would prefer that you fix up the ones that are related indeed (such as ENV/ARG and the SAML thing). Thanks.

Hello @pierrecdn !

I did the rebase for commits. Do you mind check it again?

Thank you!

**Comment by pierrecdn** [comment]
Done, many thanks!

**Pull request merged**
